### ISSUE TITLE
Task Creation - Description CharLimit

### ISSUE THREAD

**Issue by ghost** [CMPUT301W18T11/WhoseLineIsItAnyway#11]
Currently the charlimit is inf; adjust to 300.

**Comment by lucasthalen** [comment]
CreateTaskUI
- Layout.xml
    + Set etxt_Description android:maxLength to 300

- .java
    + Adapted TextChanged to give a warning on 300 chr hit for Description field.

Fixed Commit #3beb247c761260cbff059e72145af17f06c70c0f

**Comment by ghost** [comment]
CreateTaskUI
- Layout.xml
    + Set etxt_Description android:maxLength to 300

- .java
    + Adapted TextChanged to give a warning on 300 chr hit for Description field.

Fixed Commit #3beb247c761260cbff059e72145af17f06c70c0f
