### ISSUE TITLE
Wow factor not present on wiki

### ISSUE THREAD

**Issue by samueldolha** [CMPUT301W18T11/WhoseLineIsItAnyway#4]

**Comment by ghost** [comment]
Presently it has been placed under [Roadmap Milestone 4](https://github.com/CMPUT301W18T11/WhoseLineIsItAnyway/wiki/Roadmap#deliverables-3), as this seems to be where most development on the user profiles will be.

**Fixed Commit #[cf8d794](https://github.com/CMPUT301W18T11/WhoseLineIsItAnyway/wiki/Roadmap/cf8d7945d3834d794e62d169e4decba4b5e0867a)**
